import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { FileText, Download, TrendingUp, AlertCircle, RefreshCw, Bot, ArrowLeft } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const FinancialStatements = ({ onBack }) => {
    const [activeTab, setActiveTab] = useState('pl'); // 'pl' | 'bs' | 'cf'
    const [report, setReport] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [inThousands, setInThousands] = useState(false); // Tax Mode

    useEffect(() => {
        fetchReport();
    }, []);

    const fetchReport = async () => {
        try {
            setLoading(true);
            const token = localStorage.getItem('token');
            const res = await axios.get('/api/company/trial-balance', {
                headers: { 'Authorization': `Bearer ${token}` }
            });
            setReport(res.data.report || []);
        } catch (err) {
            setError("Failed to load financial data.");
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    // --- Calculation Logic ---
    const scale = inThousands ? 1000 : 1;

    // 1. Profit & Loss Data
    const revenue = report.filter(r => r.code.startsWith('4'));
    const costOfSales = report.filter(r => r.code.startsWith('5')); // Assuming 5 is COS
    const expenses = report.filter(r => r.code.startsWith('6') || r.code.startsWith('7') || r.code.startsWith('8') || r.code.startsWith('9'));

    const totalRev = revenue.reduce((sum, r) => sum + r.crKHR, 0) / scale;
    const totalCOS = costOfSales.reduce((sum, r) => sum + r.drKHR, 0) / scale;
    const grossProfit = totalRev - totalCOS;
    const totalExp = expenses.reduce((sum, r) => sum + r.drKHR, 0) / scale;
    const netProfit = grossProfit - totalExp;

    // 2. Balance Sheet Data
    const assets = report.filter(r => r.code.startsWith('1'));
    const liabilities = report.filter(r => r.code.startsWith('2'));
    const equity = report.filter(r => r.code.startsWith('3'));

    const totalAssets = assets.reduce((sum, r) => sum + (r.drKHR - r.crKHR), 0) / scale;
    const totalLiabs = liabilities.reduce((sum, r) => sum + (r.crKHR - r.drKHR), 0) / scale;
    const totalEquity = equity.reduce((sum, r) => sum + (r.crKHR - r.drKHR), 0) / scale;

    // Balance Check: Assets = Liabs + Equity + NetProfit(Retained Earnings addition)
    const checkDiff = totalAssets - (totalLiabs + totalEquity + netProfit);

    const handleDownloadPDF = () => {
        const doc = new jsPDF();
        doc.setFontSize(18);
        doc.text(activeTab === 'pl' ? "Statement of Profit or Loss" : "Statement of Financial Position", 14, 20);
        doc.setFontSize(10);
        doc.text(`As of ${new Date().toLocaleDateString()}`, 14, 28);

        // Use autoTable based on active view... (Simplified for now)
        doc.save("Financial_Statement.pdf");
    };

    const renderRow = (label, value, bold = false, indent = false) => (
        <tr className={`border-b border-gray-100 hover:bg-gray-50 ${bold ? 'font-bold bg-gray-50' : ''}`}>
            <td className={`p-3 ${indent ? 'pl-8' : 'pl-4'} text-gray-800`}>{label}</td>
            <td className="p-3 text-right font-mono text-gray-900">
                {value !== 0 ? value.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 }) : '-'}
            </td>
        </tr>
    );

    const renderSectionHeader = (title) => (
        <tr className="bg-blue-50/50 border-b border-blue-100">
            <td colSpan="2" className="p-3 pl-4 font-bold text-blue-800 uppercase text-xs tracking-wider">{title}</td>
        </tr>
    );

    if (loading) return <div className="p-10 text-center text-gray-500">Generating Financial Statements...</div>;

    return (
        <div className="flex flex-col h-full bg-gray-50/50 animate-fade-in">
            {/* Header / Toolbar */}
            <div className="bg-white border-b border-gray-200 px-8 py-5 flex justify-between items-center shadow-sm">
                <div className="flex items-center gap-4">
                    <button onClick={onBack} className="p-2 hover:bg-gray-100 rounded-full text-gray-500 transition">
                        <ArrowLeft size={20} />
                    </button>
                    <div>
                        <h1 className="text-2xl font-bold text-gray-900 font-serif">Financial Statements</h1>
                        <p className="text-sm text-gray-500 flex items-center gap-2">
                            <Bot size={14} className="text-blue-500" />
                            Generated by Blue Agent (IAS/IFRS Compliant)
                        </p>
                    </div>
                </div>
                <div className="flex items-center gap-4">
                    <label className="flex items-center gap-2 cursor-pointer select-none bg-gray-100 px-3 py-1.5 rounded-lg border border-gray-200 hover:bg-gray-200 transition">
                        <input
                            type="checkbox"
                            checked={inThousands}
                            onChange={(e) => setInThousands(e.target.checked)}
                            className="rounded text-blue-600 focus:ring-blue-500 h-4 w-4"
                        />
                        <span className="text-gray-700 font-sans text-xs font-semibold">Values in {inThousands ? "KHR'000" : "KHR"}</span>
                    </label>
                    <button onClick={handleDownloadPDF} className="bg-gray-900 hover:bg-black text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition shadow-md">
                        <Download size={16} /> Export PDF
                    </button>
                </div>
            </div>

            {/* Blue Agent Insight Banner */}
            <div className="bg-indigo-900 text-white px-8 py-3 flex justify-between items-center text-sm shadow-md">
                <div className="flex items-center gap-3">
                    <div className="bg-white/10 p-1.5 rounded-lg"><TrendingUp size={16} className="text-indigo-200" /></div>
                    <span>
                        <span className="font-bold text-indigo-200">AI Insight: </span>
                        Net Profit Margin is <span className="font-bold text-white">{(totalRev > 0 ? (netProfit / totalRev) * 100 : 0).toFixed(1)}%</span>.
                        {checkDiff !== 0 && <span className="text-red-300 ml-2 font-bold flex items-center gap-1 inline-flex"><AlertCircle size={14} /> Balance Sheet is out by {checkDiff.toFixed(2)}</span>}
                    </span>
                </div>
                <div className="flex gap-4 font-mono text-xs opacity-80">
                    <span>Code Standard: TOI-2025</span>
                    <span>Currency: KHR</span>
                </div>
            </div>

            {/* Tabs & Content */}
            <div className="flex-1 overflow-hidden flex flex-col max-w-5xl mx-auto w-full p-8">
                {/* Tabs */}
                <div className="flex gap-2 mb-0">
                    <button
                        onClick={() => setActiveTab('pl')}
                        className={`px-6 py-3 rounded-t-xl font-medium text-sm transition-all ${activeTab === 'pl' ? 'bg-white text-blue-700 shadow-sm border-t border-x border-gray-200' : 'bg-gray-100 text-gray-500 hover:bg-gray-200'}`}
                    >
                        Profit & Loss (P&L)
                    </button>
                    <button
                        onClick={() => setActiveTab('bs')}
                        className={`px-6 py-3 rounded-t-xl font-medium text-sm transition-all ${activeTab === 'bs' ? 'bg-white text-blue-700 shadow-sm border-t border-x border-gray-200' : 'bg-gray-100 text-gray-500 hover:bg-gray-200'}`}
                    >
                        Balance Sheet
                    </button>
                </div>

                {/* Report Paper */}
                <div className="bg-white rounded-b-xl rounded-tr-xl shadow-xl border border-gray-200 p-10 min-h-[600px] font-serif relative overflow-auto">
                    {/* Watermark */}
                    <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-gray-50 text-[100px] font-bold rotate-45 pointer-events-none select-none uppercase">
                        {error ? "ERROR" : "DRAFT"}
                    </div>

                    <div className="text-center mb-8">
                        <h2 className="text-2xl font-bold text-gray-900 uppercase tracking-widest mb-2">Company Name Here</h2>
                        <h3 className="text-lg font-bold text-gray-600 mb-1">
                            {activeTab === 'pl' ? 'STATEMENT OF PROFIT OR LOSS' : 'STATEMENT OF FINANCIAL POSITION'}
                        </h3>
                        <p className="text-sm text-gray-500 italic">For the year ended 31 December {new Date().getFullYear()}</p>
                        <p className="text-xs text-gray-400 mt-2 uppercase font-sans">
                            (Expressed in {inThousands ? "thousands of Cambodian Riel" : "Cambodian Riel"})
                        </p>
                    </div>

                    <table className="w-full text-sm">

                        {/* PROFIT AND LOSS */}
                        {activeTab === 'pl' && (
                            <tbody>
                                {renderSectionHeader("Revenue")}
                                {revenue.map(r => renderRow(r.description, r.crKHR / scale, false, true))}
                                {renderRow("Total Revenue", totalRev, true)}

                                {renderSectionHeader("Cost of Sales")}
                                {costOfSales.map(r => renderRow(r.description, r.drKHR / scale, false, true))}
                                {renderRow("Gross Profit", grossProfit, true)}

                                {renderSectionHeader("Operating Expenses")}
                                {expenses.map(r => renderRow(r.description, r.drKHR / scale, false, true))}
                                {renderRow("Total Operating Expenses", totalExp, true)}

                                <tr className="h-4"></tr>
                                <tr className="border-t-2 border-black border-b-2 border-double">
                                    <td className="p-4 font-bold text-lg">NET PROFIT FOR THE YEAR</td>
                                    <td className="p-4 text-right font-bold font-mono text-lg">{netProfit.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 })}</td>
                                </tr>
                            </tbody>
                        )}

                        {/* BALANCE SHEET */}
                        {activeTab === 'bs' && (
                            <tbody>
                                {renderSectionHeader("ASSETS")}
                                {assets.map(r => renderRow(r.description, (r.drKHR - r.crKHR) / scale, false, true))}
                                {renderRow("TOTAL ASSETS", totalAssets, true)}

                                <tr className="h-6"></tr>

                                {renderSectionHeader("EQUITY & LIABILITIES")}

                                {renderSectionHeader("Equity")}
                                {equity.map(r => renderRow(r.description, (r.crKHR - r.drKHR) / scale, false, true))}
                                {renderRow("Current Year Earnings", netProfit, false, true)} {/* Auto Inserted */}
                                {renderRow("Total Equity", totalEquity + netProfit, true)}

                                {renderSectionHeader("Liabilities")}
                                {liabilities.map(r => renderRow(r.description, (r.crKHR - r.drKHR) / scale, false, true))}
                                {renderRow("Total Liabilities", totalLiabs, true)}

                                <tr className="h-4"></tr>
                                <tr className="border-t-2 border-black border-b-2 border-double">
                                    <td className="p-4 font-bold text-lg">TOTAL EQUITY & LIABILITIES</td>
                                    <td className="p-4 text-right font-bold font-mono text-lg">{(totalLiabs + totalEquity + netProfit).toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 })}</td>
                                </tr>
                            </tbody>
                        )}
                    </table>

                    <div className="mt-12 pt-8 border-t border-gray-300 flex justify-between text-xs text-center text-gray-500 font-sans">
                        <div className="w-1/3">
                            <div className="h-16 border-b border-gray-300 mb-2"></div>
                            <p>Prepared by</p>
                            <p className="font-bold">Blue AI Agent</p>
                        </div>
                        <div className="w-1/3">
                            <div className="h-16 border-b border-gray-300 mb-2"></div>
                            <p>Reviewed by</p>
                            <p className="font-bold">Finance Manager</p>
                        </div>
                        <div className="w-1/3">
                            <div className="h-16 border-b border-gray-300 mb-2"></div>
                            <p>Approved by</p>
                            <p className="font-bold">Director</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default FinancialStatements;
