const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');

async function fixKnowledge() {
    // 1. Elevate GKSMART to Admin so they can see the knowledge
    const URI = 'mongodb+srv://admin_gsk:admingsk1235@cluster0.pipzn70.mongodb.net/gksmart_live?appName=Cluster0';
    try {
        await mongoose.connect(URI);
        const res = await mongoose.connection.db.collection('users').updateOne(
            { username: 'GKSMART' },
            { $set: { role: 'admin' } }
        );
        console.log(`Elevated GKSMART to admin: ${res.modifiedCount} updated.`);
        await mongoose.disconnect();
    } catch (e) {
        console.error('User elevation failed:', e.message);
    }

    // 2. Create the 4th category: BR_Template
    const baseDir = path.resolve(__dirname, '../../knowledge/extracted');
    const brDir = path.join(baseDir, 'BR_Template');
    if (!fs.existsSync(brDir)) {
        fs.mkdirSync(brDir, { recursive: true });
        console.log(`Created directory: ${brDir}`);
    }

    const templateFile = path.join(brDir, 'Bank_Reconciliation_Standard.md');
    if (!fs.existsSync(templateFile)) {
        const content = `# Bank Reconciliation (BR) Template

This is a standard template for Bank Reconciliation processing within the GK Smart Ai system.

## 1. Summary Registry
- **Statement Period**: [START_DATE] to [END_DATE]
- **Opening Balance**: [AMOUNT]
- **Closing Balance**: [AMOUNT]
- **Total Money In**: [AMOUNT]
- **Total Money Out**: [AMOUNT]

## 2. Reconciled Items
The following items have been verified and matched using the "Exactly Matched" logic.
- Item Id: [ID] | Match: [DESCRIPTION] | Status: [MATCHED]

## 3. Discrepancy Log
- [ ] Orphaned Transactions (In Statement, not in Books)
- [ ] Missing Vouchers (In Books, not in Statement)

## 4. Final Approvals
- Generated By: GK Smart Ai (Blue Agent)
- Verified By: [ACCOUNTANT_NAME]
- Timestamp: [TIMESTAMP]
`;
        fs.writeFileSync(templateFile, content);
        console.log(`Created template file: ${templateFile}`);
    } else {
        console.log(`Template file already exists: ${templateFile}`);
    }
    process.exit(0);
}

fixKnowledge();
